spring:
  application:
         name: CompanyV1
  datasource:
    username: root
    password: Maxak351#
    url: jdbc:mysql://localhost:3306/stockmarket
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoint:
        info:
           enabled: true
        bean:
           enabled: true
        env:
           enabled: true
  port: 8082
  security:
      enabled: true

server:
  port: 8082

logging:
  level:
    org.springframework.web: ERROR
    com.market.savecompany: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: <logPath>/test.log
